# Jykell configuration
# highlighter: pygments
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
  auto_ids: true
  input: GFM
  toc_levels: 1..2

highlighter: none
paginate: 15
language: 'en-uk'
host_url: 'https://draveness.me'

# Website info
name: '面向信仰编程'
description: "Draveness's Blog"

# Author's info
author: 'Draveness'
# edit 'categories' in the front matter of every post to match this username
nickname: draveness
bio: 'Rails / Elixir / iOS'
location: 'Beijing, China'
url: 'https://draveness.me'
img_url: 'https://img.draveness.me'
image: 'assets/images/draven.png'

short_url: 'draveness.me'
google_analytics: UA-56898419-1
disqus: draveness
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
# permalink: /:title
permalink: pretty
# permalink: /tag/:tag

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-toc
whitelist:
  - jekyll-redirect-from

exclude: [vendor]

sass:
  style: compressed

safe: false
lsi: false
username: draveness
repo: jekyll-blog
branch: master
# relative_source: ../jasper/
# destination: ../jasper-pages/
production_url:  https://biomadeira.github.io/jasper/
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
